// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fUERLDF7B6PkVocLHV4JH5
// Component: MhPMGXp3nWSl

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: fUERLDF7B6PkVocLHV4JH5/projectcss
import sty from "./PlasmicComponentTwo.module.css"; // plasmic-import: MhPMGXp3nWSl/css

createPlasmicElementProxy;

export type PlasmicComponentTwo__VariantMembers = {};
export type PlasmicComponentTwo__VariantsArgs = {};
type VariantPropType = keyof PlasmicComponentTwo__VariantsArgs;
export const PlasmicComponentTwo__VariantProps = new Array<VariantPropType>();

export type PlasmicComponentTwo__ArgsType = {};
type ArgPropType = keyof PlasmicComponentTwo__ArgsType;
export const PlasmicComponentTwo__ArgProps = new Array<ArgPropType>();

export type PlasmicComponentTwo__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultComponentTwoProps {
  className?: string;
}

const $$ = {};

function PlasmicComponentTwo__RenderFunc(props: {
  variants: PlasmicComponentTwo__VariantsArgs;
  args: PlasmicComponentTwo__ArgsType;
  overrides: PlasmicComponentTwo__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicComponentTwo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicComponentTwo__VariantsArgs;
    args?: PlasmicComponentTwo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicComponentTwo__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicComponentTwo__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicComponentTwo__ArgProps,
          internalVariantPropNames: PlasmicComponentTwo__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicComponentTwo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicComponentTwo";
  } else {
    func.displayName = `PlasmicComponentTwo.${nodeName}`;
  }
  return func;
}

export const PlasmicComponentTwo = Object.assign(
  // Top-level PlasmicComponentTwo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicComponentTwo
    internalVariantProps: PlasmicComponentTwo__VariantProps,
    internalArgProps: PlasmicComponentTwo__ArgProps
  }
);

export default PlasmicComponentTwo;
/* prettier-ignore-end */
